### ISSUE TITLE
This program is fantastic EXCEPT that the mouse icon shows a terrible white jaggy halo around it.

### ISSUE THREAD

**Issue by MichaelVParent** [Phaiax/PxKeystrokesForScreencasts#38] opened 2019-12-13 21:27 UTC
I'm a graphic artist. Can anyone who can branch this program make it so I or users can swap out the mouse icon images? If that were possible this would be the best program out there of its kind.

**Comment by Phaiax** [comment] 2019-12-14 00:47
Hey. If you can make better icon, I'll gladly change it.

**Comment by MichaelVParent** [comment] 2019-12-14 00:54
Excellent. Can you please send me the current ones as a size guide? 
Also, would it be possible to add an option to let people select from a 
variety or even edit png's in a folder that it would use? this would 
allow for maximum flexibility for the users.

cheers,
Mike

**Comment by Phaiax** [comment] 2019-12-14 09:37
See here:
https://github.com/Phaiax/PxKeystrokesForScreencasts/tree/master/PxKeystrokesUi/Resources

**Comment by Phaiax** [comment] 2019-12-14 09:48
When I created the programm, I only had a normal-dpi screen, but now I have a high-dpi screen, too. 
So maybe doubleing the height and width would be appropiate. Vector graphics would be better, but that is not an absolute requirement, so use what you are best in. (I would still ship .pngs with the programm).

PS: Your work would be licensed under the apache license (https://github.com/Phaiax/PxKeystrokesForScreencasts/blob/master/LICENSE). And it would be nice if you could also provide the source files (.psd or whatever)

**Comment by MichaelVParent** [comment] 2019-12-15 07:58
I have no problem with that license and I will provide the PSD files, 
likely created with basic Photoshop vector shapes.

something strange is happening though, I downloaded all the PNG images 
and they are all not able to be loaded by windows or Photoshop, like 
they are corrupted. Can you possibly zip up tall the mouse image files 
and email them to me?

Thanks,
Mike

**Comment by MichaelVParent** [comment] 2019-12-17 07:03
Hi again,

Did you receive my previous email. I really want to make new art for the 
app, but I need working PNG images to base general size on etc.

Thanks,

Mike

previous email message 
below______________________________________________________________________


I have no problem with that license and I will provide the PSD files, 
likely created with basic Photoshop vector shapes.

something strange is happening though, I downloaded all the PNG images 
and they are all not able to be loaded by windows or Photoshop, like 
they are corrupted. Can you possibly zip up tall the mouse image files 
and email them to me?

Thanks,
Mike

**Comment by Phaiax** [comment] 2019-12-17 18:00
Sry, I read the mail on mobile and then I forgot about it. Here are the current images as zip:

https://github.com/Phaiax/PxKeystrokesForScreencasts/raw/store/PKFSPictures.zip

**Comment by MichaelVParent** [comment] 2019-12-17 18:18
Perfect.  These files all work.

thanks very much,

Mike

**Comment by MichaelVParent** [comment] 2019-12-19 07:38
Hi again,

I loaded your PNG images into Photoshop and there didn't seem to be any 
of the white edges that appear when I run the program. This makes me 
thing that either my computer doesn't like how your program displays the 
PNG images, or the PNG images are saved in a format that results in 
white artifacts when displayed. by your program.

I just loaded the images and re-saved them out with another program to 
see if they are now in a more friendly format which will avoid the white 
edge pixels.

Can you please make a new build which uses these re-exported PNG files 
so I can see if the white artifacts no longer appear?

Thanks,
Mike

**Comment by MichaelVParent** [comment] 2019-12-19 07:46
Here are the reexported files and a screen grab showing the current white artifacts around all png's your program displays.
[REExportedPKFSPictures.zip](https://github.com/Phaiax/PxKeystrokesForScreencasts/files/3982292/REExportedPKFSPictures.zip)
![WhiteArtifacts](https://user-images.githubusercontent.com/8163137/71154518-f9f1a700-223b-11ea-81d3-1daf5fb3e077.png)

**Comment by Phaiax** [comment] 2019-12-29 16:49
Tried it with the new pngs. Its still white around the edges. I think the problem is somewhere else, but I try to investigate.

**Comment by MichaelVParent** [comment] 2019-12-29 17:14
Thanks very much.

**Comment by Phaiax** [comment] 2019-12-29 22:20
Try this one: [PxKeystrokesUi.exe (Test)](https://github.com/Phaiax/PxKeystrokesForScreencasts/raw/store/PxKeystrokesUi.exe)

I completely changed how the images are drawn.

Please note also:
1. You should not need to change any compatibility settings (highdpi stuff) anymore. 
2. The settings window is currently messed up. I don't know how to fix that yet.
3. It only works with Windows 10
3. You need .NET Framework 4.8. Should be automatically installed if you have the newest Windows 10 installed.

If you still have better ideas for icons, please give them a shot.

**Comment by MichaelVParent** [comment] 2019-12-30 12:58
Confirmed the white outline issue is fixed! Would you be able to make it 
so that if someone has a folder called "mouse_images" in the same root 
folder as the .exe file then it would use the mouse images from that 
folder. The goal is to not only let me customize the images as I need 
to, but let all future users customize them as they need for their projects.

In my case I need pixel art versions.

If you add the ability to choose from different images or ideally even 
add custom ones I'll donate any variants I make.

thanks,
Mike

**Comment by Phaiax** [comment] 2020-05-13 19:14
Will be fixed with v2.0 release. But since it already works in the current development version, I'll close this.

**Closed by Phaiax** 2020-05-13 19:14 UTC
