### ISSUE TITLE
Scale or 2 monitor problem

### ISSUE THREAD

**Issue by Ogi22po** [Phaiax/PxKeystrokesForScreencasts#29] opened 2018-02-13 22:28 UTC
Pleas look at screenshots.
You will see.
![2018-02-13 23_21_49-](https://user-images.githubusercontent.com/36459820/36177284-81f804ee-1115-11e8-967e-d3713efef608.jpg)
![2018-02-13 23_22_04-](https://user-images.githubusercontent.com/36459820/36177285-8210deba-1115-11e8-9ded-339cd5a8d712.jpg)
![2018-02-13 23_22_19-](https://user-images.githubusercontent.com/36459820/36177286-822b7dd8-1115-11e8-9034-b78f5a80356b.jpg)
![2018-02-13 23_22_27-win8keystrokesforscreencasts](https://user-images.githubusercontent.com/36459820/36177287-82458570-1115-11e8-87f4-0e6ea7f9a287.jpg)

**Comment by Ogi22po** [comment] 2018-02-13 22:32
maybe a problem with scale only
![2018-02-13 23_30_18-](https://user-images.githubusercontent.com/36459820/36177500-2cb264ec-1116-11e8-8fbf-1df317650109.jpg)
![2018-02-13 23_30_25-nastavenia](https://user-images.githubusercontent.com/36459820/36177501-2ccca5b4-1116-11e8-899f-139d5d00704b.jpg)

**Comment by PixelatedPope** [comment] 2018-10-17 16:10
Yup, same issue with a single monitor at 200%.

**Comment by DerAndere1** [comment] 2019-03-05 18:20
Confirmed. The halo (indicator for mouse pointer) position is offset from the mouse pointer by the DPI scaling factor.
Maybe this helps: https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Comment by DerAndere1** [comment] 2019-03-05 20:11
A workaround is to navigate to the executable of PxKeystrokesUI (e.g. in .../PxKeystrokesUI/releases/v0.3.1, press the right mouse button (RMB) on the PxKeystrokesUI.exe and in the context menu for PxKeystrokesUI.exe  press left mouse button (LMB) on Preferences  -> compatibility -> change High-DPI settings. LMB on the checkbox to enable the option "Overwrite DPI-Scaling". Keep the default option "Application" from the drop down list selected to enable overwriting high-DPI-scaling by the application. LMB on "OK".

**Comment by DerAndere1** [comment] 2019-03-08 00:03
Duplicate of #28

**Comment by Phaiax** [comment] 2020-05-13 19:17
Will be fixed soon, I am working on a new version that supports multi dpi setups. Closing this issue since there are a lot of duplicates 😸

**Closed by Phaiax** 2020-05-13 19:17 UTC
Labels: nominated
