### ISSUE TITLE
Indicate cursor position 

### ISSUE THREAD

**Issue by mvillatoroalvarez** [Phaiax/PxKeystrokesForScreencasts#28] opened 2017-11-30 15:58 UTC
![up left corner](https://user-images.githubusercontent.com/29682940/33440606-6d1c7a60-d5be-11e7-9eef-a499898156bc.png)

![donw right corner](https://user-images.githubusercontent.com/29682940/33440607-6d2707d2-d5be-11e7-8d5b-73a8adfbd66f.png)

Windows cursor doesn't match with Px Keystrokes Cursor position. Start ok in the up left corner but, on the way to the down right corner the cursor separate a lot from the mouse pointer.

**Comment by ahalekelly** [comment] 2018-01-12 02:27
I have the same issue, it seems to be caused by Windows display scaling. It doesn't happen when scaling is set to 100%

**Comment by mvillatoroalvarez** [comment] 2018-01-12 02:29
You are right. Thanks

**Comment by DerAndere1** [comment] 2019-03-08 00:04
A better workaround is to navigate to the executable of PxKeystrokesUI (e.g. in .../PxKeystrokesUI/releases/v0.3.1, press the right mouse button (RMB) on the PxKeystrokesUI.exe and in the context menu for PxKeystrokesUI.exe press left mouse button (LMB) on Preferences -> compatibility -> change High-DPI settings. LMB on the checkbox to enable the option "Overwrite DPI-Scaling". Keep the default option "Application" from the drop down list selected to enable overwriting high-DPI-scaling by the application. LMB on "OK". For more info see https://blogs.windows.com/buildingapps/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/

**Comment by Phaiax** [comment] 2020-05-13 19:17
Will be fixed soon, I am working on a new version that supports multi dpi setups. Closing this issue since there are a lot of duplicates 😸

**Closed by Phaiax** 2020-05-13 19:17 UTC
